apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
<<<<<<< HEAD
        image: kariusdi/fastapi_microservice:local
=======
        image: kariusdi/fastapi_microservice:v3.2
>>>>>>> origin/main
        ports:
        - containerPort: 8000