apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kariusdi/fastapi_microservice:v2.0
        env:
          - name: FRONTEND_HOST
            value: frontend  # Use the service name created for API
          - name: FRONTEND_PORT
            value: "80"
        ports:
        - containerPort: 8000

