#Imperative command to create service to expose api deployment 
#kubectl expose deploy api \ --name=api \ --type=LoadBalancer \ --port=80 \ --target-port=8000
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  # type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      # Optional field# By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 32409
  type: LoadBalancer