apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: konmake
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
    containers:
    - name: frontend
      image: kariusdi/kariusdi/reactapp_microservice:v1.0
      ports:
      - containerPort: 5173