apiVersion: v1
kind: Pod
metadata:
  name: queue
spec:
  containers:
    - name: api
      image: kariusdi/fastapi_microservice:v3.2
      ports:
        - name: api 
          containerPort: 8000
    - name: frontend
      image: kariusdi/reactapp_microservice:v3.2
      ports:
       - name: frontend 
         containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: frontend
      port: 3000
      targetPort: 5173
      # Optional field# By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30330
    - name: api
      port: 80
      targetPort: 8000
      nodePort: 32409
  # type: LoadBalancer
